### ISSUE TITLE
Translation problem (mixed languages,etc)

### ISSUE THREAD

**Issue by MaddyTintinger** [yesiman/INRAE.VINEAS#26]
Please add a comment with the translations issues you can see. Please add screenshot to make resolutions easier

**Comment by AlenAlbreht** [comment]
When choosing language in the language bar, "Slovenian" has some unusual characters. It should read "Slovenščina".
![Screenshot 2021-02-08 11 05 48](https://user-images.githubusercontent.com/77341714/107205389-19c6ca00-69fe-11eb-8209-2788b0df7f40.png)

**Comment by AlenAlbreht** [comment]
When you explore the map, there is this "Filtres" purple section on the left-hand side. I assume this is in French, in Slovenian it should read "Filtri". Also, there aren't any filters to choose?

![Screenshot 2021-02-08 11 13 59](https://user-images.githubusercontent.com/77341714/107206190-010ae400-69ff-11eb-8cfb-c753a85b8c19.png)

**Comment by AlenAlbreht** [comment]
On the first page, "agenda" is currently translated into Slovenian as "dnevni red". The translation would be much better if it would read "DOGODKI". Also, just under this title, there is "DOGODKI NA+DATE" - there should be a spece between the text and the date. This is an issue in all languages. If I click on this tab, I get a calendar in English and it says "no events" in eglish on the right-hand side. This should be translated into Slovene.

![Screenshot 2021-02-08 11 18 38](https://user-images.githubusercontent.com/77341714/107206672-a32acc00-69ff-11eb-8dec-39418344aebd.png)

**Comment by AlenAlbreht** [comment]
If I click on the "VPLIVI PODNEBNIH SPREMEMB" on the main page, I get the infographics in French, which is understandable since the material has not been produced yet, but the title of the page is also in French.

![Screenshot 2021-02-08 11 26 16](https://user-images.githubusercontent.com/77341714/107207539-b25e4980-6a00-11eb-81f2-b76b2f0000cb.png)

**Comment by AlenAlbreht** [comment]
Under "REŠITVE IN VZVODI" there is one technical domain which is still in French - "Matériel végétal"

![Screenshot 2021-02-08 11 29 00](https://user-images.githubusercontent.com/77341714/107207810-0b2de200-6a01-11eb-8e2f-6a65756a49ef.png)

**Comment by AlenAlbreht** [comment]
Under generic solutions, "parahail mreže" should be replaced by "protitočne mreže"

![Screenshot 2021-02-08 11 31 31](https://user-images.githubusercontent.com/77341714/107208056-57792200-6a01-11eb-8fca-8f426e54cc7d.png)

**Comment by AlenAlbreht** [comment]
Under network map "FILTRES" should be translated into "FILTRI"

![Screenshot 2021-02-08 12 02 47](https://user-images.githubusercontent.com/77341714/107211352-b8a2f480-6a05-11eb-89db-5ec986631be5.png)

**Comment by AlenAlbreht** [comment]
Under geographical information nothing seems to be translated into Slovene (left-hand side). Also, under "VINE DATA", "Vinorodni" should maybe be translated into "Slovenija" or "Vinorodne pokrajine Slovenije" which means "Vine regions of Slovenia". These descriptions should propably be consistent between countries.

![Screenshot 2021-02-08 12 05 30](https://user-images.githubusercontent.com/77341714/107211575-0c154280-6a06-11eb-8a28-165cc96b6c6c.png)

**Comment by AlenAlbreht** [comment]
Under solutions --> technical domains, there is one still in French - "Matériel végétal".

![Screenshot 2021-02-08 12 12 12](https://user-images.githubusercontent.com/77341714/107212300-0cfaa400-6a07-11eb-9f3f-456e2ebd638f.png)

**Comment by AlenAlbreht** [comment]
When I go to the sign in page, "submit" button is currently translated into Slovene as "objavi". A much better translation would be "PRIJAVA"

![Screenshot 2021-02-08 12 15 54](https://user-images.githubusercontent.com/77341714/107212759-b9d52100-6a07-11eb-86df-5fe70a7235b8.png)

**Comment by AlenAlbreht** [comment]
If I click on the MEDCLIV logo on the top right-hand side of the VINEAS page, it directs me to a mixed SLO-ENG page.

![Screenshot 2021-02-08 12 20 35](https://user-images.githubusercontent.com/77341714/107213061-2819e380-6a08-11eb-8f0b-3fcc259bbd45.png)

**Comment by eccele** [comment]
In the Italian case, the MEDCLIV page is not mixed (except the keywords), but there is this part that comes out also in other cases that is in French:

RECHERCHER --> VOS MOTS CLES

<img width="255" alt="Immagine" src="https://user-images.githubusercontent.com/9801331/107610662-669ae280-6c42-11eb-8752-f5ffdb19b13f.png">

**Comment by MaddyTintinger** [comment]
> When you explore the map, there is this "Filtres" purple section on the left-hand side. I assume this is in French, in Slovenian it should read "Filtri". Also, under "TARČNI SEKTORJI", all the text is in French.
> 
> ![Screenshot 2021-02-08 11 13 59](https://user-images.githubusercontent.com/77341714/107206190-010ae400-69ff-11eb-8cfb-c753a85b8c19.png)

We will delete the target sectors filter in the map as the actor are only related to viticulture or winemaking

**Comment by eccele** [comment]
When I enter "register" in Italian (only), this image should read: "REGISTRATI", instead there is the reference to an automatic translator.

![image](https://user-images.githubusercontent.com/9801331/107611212-c47bfa00-6c43-11eb-996d-de834e7911fb.png)


Other issue: why asking for a motivation? I would for sure remove that field, I don't see any usefulness and it is somewhat annoying...

**Comment by MaddyTintinger** [comment]
> Under geographical information nothing seems to be translated into Slovene (left-hand side). Also, under "VINE DATA", "Vinorodni" should maybe be translated into "Slovenija" or "Vinorodne pokrajine Slovenije" which means "Vine regions of Slovenia". These descriptions should propably be consistent between countries.
> 
> ![Screenshot 2021-02-08 12 05 30](https://user-images.githubusercontent.com/77341714/107211575-0c154280-6a06-11eb-8a28-165cc96b6c6c.png)

I ask the person in charge of the GIS map to change the legend in order to homogenise for all countries, I hope he will do that soon

**Comment by MaddyTintinger** [comment]
> POTRDI

Done

**Comment by eccele** [comment]
Section "Solutions and levers". At the end there is this part that is mixed Italian / French

![image](https://user-images.githubusercontent.com/9801331/107611548-86cba100-6c44-11eb-8aaf-ddb45ea08fa9.png)

**Comment by MaddyTintinger** [comment]
> If I click on the MEDCLIV logo on the top right-hand side of the VINEAS page, it directs me to a mixed SLO-ENG page.
> 
> ![Screenshot 2021-02-08 12 20 35](https://user-images.githubusercontent.com/77341714/107213061-2819e380-6a08-11eb-8f0b-3fcc259bbd45.png)

I give the rights to modify this page. Now in your dashboard > projects you have access to MEDCLIV project card. You can edit this card and translate it into slovenian. To translate :
1) click on edit
2) change the "current version" at the top of the formulaire to Slovenian
3) translate the texts
4) submit

**Comment by MaddyTintinger** [comment]
> REGISTRATI
@eccele I just made the modification but it does not appear. Below I ask to Fabrice to haev a look. 
Regarding the motivation, Marc added this option to avoid fake account (no motivation and the email adress is weird)

@yesiman Je viens de changer la traduction "s'inscrire" en Italien mais elle ne s'est pas mise à jour dans le FO... voir page d'inscription en italien

**Comment by eccele** [comment]
Now the "problem" is that (at least in Italian) I see that the reference for the project (MEDCLIV) is Alen!

![image](https://user-images.githubusercontent.com/9801331/107613187-14f55680-6c48-11eb-83dd-80a2f2dbb854.png)

17 March - the problem is still present: when one person edits (probably in any language!) the card, the latest is considered the "reference". The reference should be a static field, written only once at the beginning...

**Comment by eccele** [comment]
In the "Actor" card:

"Documento" --> "Documenti"
"Azioni" --> "Tipologia"

(THIS ALSO IN THE "MAP OF ACTORS AND PROJECTS" MENU):
![image](https://user-images.githubusercontent.com/9801331/107616473-702a4780-6c4e-11eb-96f7-7be1972cc202.png)


Note: in this list there are two important types that are missing:
- professionals
- service companies.
 
To avoid to increase too much the length of the list, I think that the two can be added to the existing spinoff / startup type, because they are all service providers. The latter words could make for this category perhaps, or in alternative, listing them all:
"service company, professional studio, spinoff, startup"

**Comment by eccele** [comment]
This is in French:

![image](https://user-images.githubusercontent.com/9801331/107616824-11190280-6c4f-11eb-8998-0a2e5db70b1e.png)

**Comment by eccele** [comment]
IN INPUT OF NEW ENTRIES: part not translated
 
![image](https://user-images.githubusercontent.com/9801331/107616914-3574df00-6c4f-11eb-9b44-e626a9f81421.png)
 
17 March:
Partially translated (not "Tri" --> "Chiave" in Italian)

**Comment by eccele** [comment]
In Actor - Access this text needs some changes:
![image](https://user-images.githubusercontent.com/9801331/107747427-b1d2f500-6d17-11eb-9d8c-fb063e088e53.png)

Please change with this:

Qui puoi dare i diritti di amministrazione ad altri utenti per questa pagina.  Se vuoi invitare altri utenti della piattaforma a contribuire al contenuto di questa pagina, digita il nome della persona nella barra di ricerca e seleziona la matita sulla sua riga per concedere specifici diritti. - Leggi: l'utente potrà vedere la pagina nel suo cruscotto personale, ma non avrà i diritti di modificarla. - Scrivi e Cancella: l'utente potrà modificare e/o cancellare la pagina. - Condividi: l'utente potrà concedere i diritti di accesso ad altri utenti.

Important: I have deleted the sentence "Se la tua pagina è completa, attiva il pulsante "Pronto per la pubblicazione" per una visualizzazione pubblica nella piattaforma." This is not related to the page "Access", where it can be read. It is probably for the "Propoerties" page (?). And in any case, what is the button "Pronto per la pubblicazione"? Probably "INVIA"?

Second issue: this pop-up is not translated in Italian:

![image](https://user-images.githubusercontent.com/9801331/107748097-cfed2500-6d18-11eb-8c6e-d66e64917f4f.png)

The meaning is not really clear: what are the sub-objects? The related objects can be understood, but... are they the same thing?

Italian translation:

Applicare ai sotto-oggetti? [OR: "oggetti collegati"??]. Sì - No - Annullare

**Comment by eccele** [comment]
When I delete an object, this non-translated pop-up appears:

![image](https://user-images.githubusercontent.com/9801331/107760829-ac32da80-6d2a-11eb-8c2c-d29bd488f22c.png)
 
Italian translation:

Confermare la cancellazione?
Conferma - Annulla


When I apply the "rights" to modify a card, this pop-up appears

![image](https://user-images.githubusercontent.com/9801331/111462159-60ef5b80-871e-11eb-8206-c3dbc6929863.png)

Translation: "Applicare ai sotto-oggetti?"  "Sì" "No" "Annullare"

**Comment by AlenAlbreht** [comment]
#1 At the bottom of a page, "STIKI" (contacts in English) - a better translation is "KONTAKT". #2 Also in the same location, the text is in French. #3 at the bottom of the page  - "GOR" should read "NA VRH" (UP in English)

![Screenshot 2021-02-15 08 23 37](https://user-images.githubusercontent.com/77341714/107917217-de7d4b80-6f67-11eb-867a-cc24fb771e4b.png)

**Comment by AlenAlbreht** [comment]
"PREJŠNJI" should read "NAZAJ". And there is also an issue, because if I browse the page in SLO language and I click on this button it directs me to the homepage but in English language instead of SLO. After clicking this button on different sub-pages I realised that it always directs me to a different page, but never to the page I was visiting prior to that (i.e. never to the "PREVIOUS" page)

![Screenshot 2021-02-15 08 31 36](https://user-images.githubusercontent.com/77341714/107917599-7713cb80-6f68-11eb-8d66-dcef7fea303f.png)

**Comment by AlenAlbreht** [comment]
At the top-most menu bar "ZA VPIS" (login in English) should read "PRIJAVA"

**Comment by AlenAlbreht** [comment]
During registration, the form in SLO should be updated a little bit in my opinion.
Currently "VAŠA AKTIVNOST" means "your activity", but it is not the best phrase when you literally translate it into SLO. I think it would be better if it said: "VAŠE PODROČJE DELA" which means "your field of work". Do I understand correctly this input field?
Also "MOTIVACIJA" (ang MOTIVATION) is maybe not very self-explanatory. I would suggest rephrasing it into "VAŠA MOTIVACIJA ZA PRIKLJUČITEV K VINEAS PLATFORMI" which would mean "your motivation for joining the VINEAS platform".

![Screenshot 2021-02-15 08 45 40](https://user-images.githubusercontent.com/77341714/107918904-cf4bcd00-6f6a-11eb-91f6-bfed50d2f6ae.png)

**Comment by AlenAlbreht** [comment]
When I am logged in and hover with my mouse over my account tab in the upper-most bar, there is the "IZPIS" option (logout in English). This should better read "ODJAVA".

![Screenshot 2021-02-15 08 53 47](https://user-images.githubusercontent.com/77341714/107919425-9b24dc00-6f6b-11eb-9409-e24f9f4f4134.png)

**Comment by AlenAlbreht** [comment]
In the field where the partners are listed NIC listing is incorrect. To resemble others, it should read "NIC - National Institute of Chemistry, Slovenia". I cannot correct for this mistake, this should be done in the system?

![Screenshot 2021-02-15 09 19 15](https://user-images.githubusercontent.com/77341714/107921590-0623e200-6f6f-11eb-9917-e4199fbd0332.png)

**Comment by AlenAlbreht** [comment]
> 
> 
> > If I click on the MEDCLIV logo on the top right-hand side of the VINEAS page, it directs me to a mixed SLO-ENG page.
> > ![Screenshot 2021-02-08 12 20 35](https://user-images.githubusercontent.com/77341714/107213061-2819e380-6a08-11eb-8f0b-3fcc259bbd45.png)
> 
> I give the rights to modify this page. Now in your dashboard > projects you have access to MEDCLIV project card. You can edit this card and translate it into slovenian. To translate :
> 
>     1. click on edit
> 
>     2. change the "current version" at the top of the formulaire to Slovenian
> 
>     3. translate the texts
> 
>     4. submit

Maddy, I made all the corrections that I could possibly do, but there are still many things to be translated into Slovene, which I am not able to do by myself (do not have the proper rights I suppose). Keywords "wine" and "vine" are still in French and I cannot correct that. Everything associated with the search box is still in French. Relations are also still in French.

![Screenshot 2021-02-15 09 35 35](https://user-images.githubusercontent.com/77341714/107923029-2d7bae80-6f71-11eb-9887-6545c2d436fb.png)

**Comment by MaddyTintinger** [comment]
@AlenAlbreht Thanks Alen for translating the Medcliv page into Slovenian. I know anything outside the text I have to do with the developer.
I made the modifications for today's comments you added. The only thnigs I could not are : "#2 Also in the same location, the text is in French. #3 at the bottom of the page - "GOR" should read "NA VRH" (UP in English)"

I gave you the rights to modify NIC Actor page, if you want to change the title. 

Can you delete the comments fixed? Thank you!

**Comment by eccele** [comment]
This part in the solution card (right column) is not fully translated into Italian and the central part is totally different (!):

image.png
![image](https://user-images.githubusercontent.com/9801331/108035215-ec4dd200-7036-11eb-9b76-4c2ecf96cf8a.png)


Here the original French:
Cette page n'a pas encore de Référent(e). Rejoignez la communauté pour gérer son contenu ! Créer vous un compte & envoyer un mail si vous souhaitez devenir référent sur une fiche

Translation in Italian:
Questa pagina non ha referenti. Associati alla comunità VINEAS per gestire i suoi contenuti! Registrati ed invia un'email se vuoi proporti come referente per questo documento.



17 March:
I don't know if the text has been translated, because I don't know how to produce it. Please Maddy, delete the comment when done.

**Comment by MaddyTintinger** [comment]
@eccele @AlenAlbreht I re-read all you comments and made a list of the issues not fixed yet (below), Can you please delete the comments that have been fixed please ? So that it will be esaier to see the real new issues. 

To be fixed:
Categories in "Action" filter (filed of action)
Pop up: Activer aux sous objets Applicare ai sotto-oggetti? [OR: "oggetti collegati"??]. Sì - No - Annullare
 Pop up:Confermare la cancellazione? Conferma - Annulla
at the bottom of the page - "GOR" should read "NA VRH" (UP in English) 
Contact in the footer

in all the cards "Réseau _ Liste _ Géographie"

**Comment by eccele** [comment]
Categories in "Action" filter (field of action): sorry, but I don't find any more this reference...

Dashboard, when deleting an object:
Pop up: Confermare la cancellazione? Conferma - Annulla --> I confirm that it is still in French

In Dashboard, "Access":  problem solved.

**Comment by eccele** [comment]
Here the original text was not translated. Now we read:
![image](https://user-images.githubusercontent.com/9801331/108374655-7c3f7780-7201-11eb-8f97-ff109581eace.png)
 "PRESENTAZIONE" makes no sense here. The correct term is "Parole chiave"

**Comment by eccele** [comment]
This is a new category of sorting the documents, but the term is not translated.

![image](https://user-images.githubusercontent.com/9801331/108375021-dcceb480-7201-11eb-923c-80b969cf2fd8.png)
 
Italian: PERTINENZA

**Comment by eccele** [comment]
In this page:
![image](https://user-images.githubusercontent.com/9801331/109028147-d046d200-76c1-11eb-84b2-03846f3b5ab9.png)

some adjustments of the Italian text are needed. First generic part: 
1. please delete the quotation marks (beginning and end).

2. Change this text:  I dettagli delle soluzioni specifiche si trovano nelle soluzioni specifiche in grigio nei risultati della ricerca ""soluzioni e leve" -->  I dettagli delle soluzioni specifiche si trovano in grigio nei risultati della ricerca "soluzioni e leve"

In the list of solutions, please see the latest version attached
[ekit_trads_1612354955693.xlsx](https://github.com/yesiman/INRAE.VINEAS/files/6037306/ekit_trads_1612354955693.xlsx)
.

**Comment by eccele** [comment]
Home page:

![image](https://user-images.githubusercontent.com/9801331/109114317-bea31000-773d-11eb-9e9d-25301e7e9c24.png)

Italian: --> LA PIATTAFORMA

AND: this link leads to the same home page...

**Comment by eccele** [comment]
In the solution and levers:

![image](https://user-images.githubusercontent.com/9801331/109468043-59685b00-7a6c-11eb-81ac-d0738e54622f.png)

***** There are a number of items that are in two categories: that should be revised! *****

Missing translations for Italian:

**AZIONI --> SCALA D'AZIONE:**
.....
- Territorio (collettività)
- Consumatori
- Cooperative, commercio... [these two don't seem similar items, however: why are they together, in such a long list?]

CAMPO D'AZIONE:
Tecnica - enologia 
Gestione - marketing
Collaborazione
Indefinito
Ricerca e innovazione
Strategia trasformativa
Pianificazione e regolamentazione

Aree tecniche:
- ....
- malattie e danni
- gestione del vigneto
- tecniche enologiche
- gestione degli eventi meteorologici


Comments:
- why Technical - oenology? And what about "Technical - agronomic"? I would delete oenology or add a similar category for agricultural items
- "Recherche et" - I think that Innovation is missing here
- "undefined" probably should go either first or last... 

and in any case, the priority is revising these keywords because there are some that are in more than one category!

**Comment by MaddyTintinger** [comment]
> This is in French:
> 
> ![image](https://user-images.githubusercontent.com/9801331/107616824-11190280-6c4f-11eb-8998-0a2e5db70b1e.png)

Bonjour @yesiman, 
Nous n'avons jamais discuté de comment traduire ces objets, j'ai les traductions, il restera à savoir comment les traduire.

MErci et à plus tard
Maddy

**Comment by eccele** [comment]
![image](https://user-images.githubusercontent.com/9801331/109941980-0264bf00-7cd4-11eb-970f-1accd76d3e5e.png)

In all languages: "Prototype" is misleading. Just "Description" would be enough
Then, the (?) has no effect and can be deleted

In Italian, the following:
![image](https://user-images.githubusercontent.com/9801331/109942198-40fa7980-7cd4-11eb-8af8-5f619188b3bb.png)
should better be written as "Documenti"

**Comment by AlenAlbreht** [comment]
On the front page the tab "LA PLATEFORME" is in French at the moment in the SLO version should read "PLATFORMA".

![Screenshot 2021-03-12 07 44 23](https://user-images.githubusercontent.com/77341714/110902865-d1edd800-8306-11eb-8e10-f59aee383a63.png)

**Comment by eccele** [comment]
When I enter / edit a solution card in English, the field "Partner" is called "Helper". This makes confusion, it should be "Partner".

**Comment by eccele** [comment]
The sorting key "Tri" is not translated. In Italian: "Chiave"

![image](https://user-images.githubusercontent.com/9801331/111313317-8158e080-8660-11eb-9694-b52f4fd77f89.png)

**Comment by eccele** [comment]
This word is not translated. Italian: FILTRI

![image](https://user-images.githubusercontent.com/9801331/111448978-3e097b00-870f-11eb-8bdc-070cc8ad1a87.png)

**Comment by AlenAlbreht** [comment]
Under "MAP", "goegraphic information" does not seem to work at all. The page does not load.

**Comment by AlenAlbreht** [comment]
> 
> 
> This word is not translated. Italian: FILTRI
> 
> ![image](https://user-images.githubusercontent.com/9801331/111448978-3e097b00-870f-11eb-8bdc-070cc8ad1a87.png)

The same problem in SLO. It should read "FILTRI".

**Comment by AlenAlbreht** [comment]
> 
> 
> #1 At the bottom of a page, "STIKI" (contacts in English) - a better translation is "KONTAKT". #2 Also in the same location, the text is in French. #3 at the bottom of the page - "GOR" should read "NA VRH" (UP in English)
> 
> ![Screenshot 2021-02-15 08 23 37](https://user-images.githubusercontent.com/77341714/107917217-de7d4b80-6f67-11eb-867a-cc24fb771e4b.png)

Below under "KONTAKT" the email address is merged with the word "na". There should be a space between the two.

**Comment by AlenAlbreht** [comment]
> 
> 
> "PREJŠNJI" should read "NAZAJ". And there is also an issue, because if I browse the page in SLO language and I click on this button it directs me to the homepage but in English language instead of SLO. After clicking this button on different sub-pages I realised that it always directs me to a different page, but never to the page I was visiting prior to that (i.e. never to the "PREVIOUS" page)
> 
> ![Screenshot 2021-02-15 08 31 36](https://user-images.githubusercontent.com/77341714/107917599-7713cb80-6f68-11eb-8d66-dcef7fea303f.png)

Now it directs me to "PROJECTS" page or any other page and not to the page I was previously on or to the homepage. I believe the "PREVIOUS" button is not working properly.

**Comment by AlenAlbreht** [comment]
Whenever I click on the VINEAS logo in the upmost left-hand side corner of the page it directs me to the ENG homepage. It should probably direct me to the SLO homepage if I am using SLO language.

**Comment by AlenAlbreht** [comment]
#1 Above the search bar it says "VINEAS - sodelovalna spletna stran za deležnike trte in vina v Sredozemlju". It would read better if word "sodelovalna" would be replaced by "kolaborativna". #2 Also, it would sound better in SLO if the main title would read "Skupaj v boju proti podnebnim spremembam" instead of "sodelovanje v boju proti podnebnim spremembam".

![Screenshot 2021-03-23 19 55 53](https://user-images.githubusercontent.com/77341714/112202690-f2286b80-8c11-11eb-9f48-27cb29435961.png)

**Comment by AlenAlbreht** [comment]
Formatting of the "PLATFORM" sub-site in SLO is inappropriate and should probably be revised to be in line with the French formatting.

![Screenshot 2021-03-23 20 03 54](https://user-images.githubusercontent.com/77341714/112203662-120c5f00-8c13-11eb-81c4-3d5c235ae083.png)

**Comment by AlenAlbreht** [comment]
on the sub-site "VPLIVI PODNEBNIH SPREMEMB" the title "Preiskava projekta MEDLCIV" should read "Anketa projekta MEDCLIV". Is it also possible to get the rights to make some final changes to the main text?

![Screenshot 2021-03-23 20 09 03](https://user-images.githubusercontent.com/77341714/112204224-b8586480-8c13-11eb-8cac-8a463509e4bd.png)

**Comment by AlenAlbreht** [comment]
Under "REŠITVE IN VZVODI"... Why is only the first column in ALL-CAPS and the other three are not? Is there a special reason for it?

![Screenshot 2021-03-23 20 13 05](https://user-images.githubusercontent.com/77341714/112204699-40d70500-8c14-11eb-942c-f93d52fa32e4.png)

**Comment by AlenAlbreht** [comment]
In the huge solutions table only the first word in the column should be capitalized and not all of them when they are being listed.

![Screenshot 2021-03-23 20 18 07](https://user-images.githubusercontent.com/77341714/112205534-2c473c80-8c15-11eb-9408-974bd82bb3a3.png)

**Comment by AlenAlbreht** [comment]
Under sub-site "KARTIRANJE" ("MAP") there is "ZEMLJEVID IGRALCEV IN PROJEKTOV" ("MAP OF ACTORS AND PROJECTS"), but I don't see any projects. What am I doing wrong?

![Screenshot 2021-03-23 20 25 39](https://user-images.githubusercontent.com/77341714/112206210-f3f42e00-8c15-11eb-8f13-c3d24faae09d.png)

**Comment by AlenAlbreht** [comment]
On the "REGISTRACIJA" (registration) page the title "PRIJAVA" should read "REGISTRACIJA".

![Screenshot 2021-03-23 20 29 10](https://user-images.githubusercontent.com/77341714/112206769-97ddd980-8c16-11eb-8821-c24155e780c9.png)

**Comment by AlenAlbreht** [comment]
On my personal dashboard on the left-hand side "Dokumente" should read "Dokumenti". Also, when I hover or click on the orange question marks in the brackets nothing happens.

![Screenshot 2021-03-23 20 31 52](https://user-images.githubusercontent.com/77341714/112207022-eee3ae80-8c16-11eb-8e11-0eab9deccead.png)

**Comment by AlenAlbreht** [comment]
I do not know what "Tri" means above the drop-down menu, but it is not Slovene. This occurs in all the menus in my dashboard. Also, as Emanuele mentioned I think we should consider removing "plain text" ("golo besedilo" in Slovene) as an option as I do not understand it either.

![Screenshot 2021-03-23 20 35 18](https://user-images.githubusercontent.com/77341714/112207562-93fe8700-8c17-11eb-986d-57a7f85eac5d.png)

**Comment by AlenAlbreht** [comment]
The part "I certify that I have the right to disseminate and upload this publication" should be translated in Slovene and should read "Potrjujem, da imam pravico razširjati in naložiti ta dokument"

![Screenshot 2021-03-23 20 41 59](https://user-images.githubusercontent.com/77341714/112208234-6c5bee80-8c18-11eb-9c52-f00e4e7b0fab.png)

**Comment by AlenAlbreht** [comment]
"BERI" should read "BRANJE", "PIŠI" should read "UREJANJE", "IZBRIŠI" should read "BRISANJE", "DELI" should read "DELJENJE", "Akcije" should read "Možnosti".

![Screenshot 2021-03-23 20 45 28](https://user-images.githubusercontent.com/77341714/112208759-015ee780-8c19-11eb-9f38-141f11431a38.png)

**Comment by AlenAlbreht** [comment]
"Akcije" should read "Izberi".

![Screenshot 2021-03-23 20 49 09](https://user-images.githubusercontent.com/77341714/112208961-3f5c0b80-8c19-11eb-8d1b-382234643cb5.png)

**Comment by AlenAlbreht** [comment]
"Journal" is in English (should be "Revija") and the description when I hover over the orange question mark is in French. Both should be translated into Slovene language.

![Screenshot 2021-03-23 20 50 46](https://user-images.githubusercontent.com/77341714/112209381-ada0ce00-8c19-11eb-84ba-8054eb6a9130.png)

**Comment by AlenAlbreht** [comment]
When I hover over the orange question mark at "Logo ali slika" ("Logo or figure") it says 250x250. Is there a unit missing?

![Screenshot 2021-03-23 20 53 43](https://user-images.githubusercontent.com/77341714/112209720-0ec8a180-8c1a-11eb-8753-d65be0360dba.png)

**Comment by AlenAlbreht** [comment]
"sorodne rešitve in vzvodi" appears twice from the drop-down menu (New actor window - "Odnosi" ("Relations"))

![Screenshot 2021-03-23 21 00 48](https://user-images.githubusercontent.com/77341714/112210462-ff962380-8c1a-11eb-9510-9dae64128773.png)

**Comment by AlenAlbreht** [comment]
Pri "Sorodnih rešitvah" ("Solution cards") are the second and the third options from the back in French and should be translated into Slovene (Domaines techniques and Domaines d'action)

![Screenshot 2021-03-23 21 06 07](https://user-images.githubusercontent.com/77341714/112211196-e346b680-8c1b-11eb-86ae-27914b03dacd.png)

**Comment by eccele** [comment]
Here the English word should be "ACTORS", not "PLAYERS"

![image](https://user-images.githubusercontent.com/9801331/112440723-eee4cb00-8d4a-11eb-8bce-5bb525756fe0.png)

**Comment by eccele** [comment]
Delete the word "Collaboration"

![image](https://user-images.githubusercontent.com/9801331/112442119-cad5b980-8d4b-11eb-95c0-8d26c891cce5.png)

**Comment by AlenAlbreht** [comment]
> 
> 
> When I delete an object, this non-translated pop-up appears:
> 
> ![image](https://user-images.githubusercontent.com/9801331/107760829-ac32da80-6d2a-11eb-8c2c-d29bd488f22c.png)
> 
> Italian translation:
> 
> Confermare la cancellazione?
> Conferma - Annulla
> 
> When I apply the "rights" to modify a card, this pop-up appears
> 
> ![image](https://user-images.githubusercontent.com/9801331/111462159-60ef5b80-871e-11eb-8206-c3dbc6929863.png)
> 
> Translation: "Applicare ai sotto-oggetti?" "Sì" "No" "Annullare"

The same issues appears in Slovenian language and it should be corrected.

**Comment by eccele** [comment]
This is a request to modify the translation of the platform description in Italian

[Heading] Connettiti alla nostra knowledge base! --> Entra nella comunità VINEAS!

This list
![image](https://user-images.githubusercontent.com/9801331/112621358-ee6f3180-8e29-11eb-9862-e1a6e658d4f1.png)

misses the paragraph marks

Identifica gli attori ed essere visibile come attore impegnato in queste sfide e mostra i tuoi progetti --> 
Identificare gli attori ed essere visibile come attore impegnato in queste sfide, mostrare i tuoi progetti

...tutte le domande che potresti avere su Vine & Wine e sul cambiamento climatico. -->
...tutte le domande che potresti avere sul cambiamento climatico per vite & vino.

VINEAS consente di esplorare soluzioni e leve generiche che mettono in scena la vasta gamma di leve e tipi di soluzioni che vanno dalle opzioni tecniche a quelle strategiche o di pianificazione. Soluzioni specifiche sono collegate a queste soluzioni generiche per esplorare la diversità delle iniziative e delle opzioni locali testate.  -->
VINEAS consente di esplorare la vasta gamma di leve e tipi di soluzioni, che vanno dalle opzioni tecniche a quelle strategiche o di pianificazione. Soluzioni specifiche sono collegate alle soluzioni generiche per esplorare la diversità delle iniziative e delle opzioni.

dandoti l'opportunità di promuoverti a livello locale o internazionale e collegandola a tutti i tuoi progetti, documenti, notizie, eventi e soluzioni. -->
dandoti l'opportunità di promuoverti a livello locale o internazionale e collegandole a tutti i tuoi progetti, documenti, notizie, eventi e soluzioni.

Capire "chi fa cosa" in una regione è una risorsa importante per indirizzare meglio rapidamente le reti di partner pertinenti, i progetti o le iniziative esistenti per qualsiasi nuova cooperazione o miglioramento delle conoscenze. -->
Capire "chi fa cosa" è una risorsa importante per organizzare meglio e rapidamente le reti di partner pertinenti, i progetti o le iniziative esistenti per qualsiasi nuova cooperazione o miglioramento delle conoscenze.

Un clic nel fumetto dell'attore sulla mappa o nell'elenco dei risultati apre il file completo dell'attore ... -->
Un clic nel logo dell'attore sulla mappa o nell'elenco dei risultati apre il file completo dell'attore...

La piattaforma VINEAS co-progettata nel progetto MEDCLIV ha lo scopo di essere ulteriormente sviluppata con la comunità degli utenti. Idee per nuove funzionalità, miglioramenti ...? Unisciti a noi su: contact at vineas.net -->
La piattaforma VINEAS, risultato di una co-progettazione nel progetto MEDCLIV, ha lo scopo di essere ulteriormente sviluppata con la comunità degli utenti. Hai idee per nuove funzionalità, miglioramenti...? Unisciti a noi o contattaci su: contact at vineas.net

**Comment by MaddyTintinger** [comment]
Thanks Emanuele (@eccele) and Alen (@AlenAlbreht), I revised everything and now VINEAS is fully translated in all language without issue!

**Comment by AlenAlbreht** [comment]
Thank you Maddy!
Just one last consideration... do you think that on the homepage below the search bar we could simply say “Welcome” (in SLO “Dobrodošli”)? I think that “...to the platform” is not really necessary.

Best wishes
Alen
